<a href="https://colab.research.google.com/github/muugi2/lab2sd/blob/master/bag_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

функц ангилах_шилжүүлэх():
1.1-р Өгөгдлийн сангаас "B"-ээр эхлэсэн кодтой ажилчпыг ялгаж авах
	IF ажилчин олдвол:
		1. 1-р өгөгдлийн сангаас 2-р өгөгдлийн санруу олдсон өгөгдлийг шилжүүлэх
		2. 1-р өгөгдлийн сангаас шилжүүлэгдсэн өгөгдлийг устгах
функц Өгөгдлийн_санг_хэвлэх(Өгөгдлийн сан):
	IF Өгөгдөл олдвол:
		Өгөгдлийг хэвлэ
	ELSE:
		"Сан хоосон байна" гэж хэвлэ

функц Өгөгдлийн_санд_өгөгдөл_нэмэх_1(Ажилчны мэдээлэл):
	1-р өгөгдлийн санд мэпээлэл нэмэх
функц Өгөгдлийн_санд_өгөгдөл_нэмэх_2(Ажилчны мэдээлэл):
	2-р өгөгдлийн санд мэпээлэл нэмэх

1. Өгөгдлийн_сан_1-г үүсгэх
2. функц Өгөгдлийн_санд_өгөгдөл_нэмэх_1(Ажилчны мэдээлэл):
3. Өгөгдлийн_сан_2-г үүсгэх
4. функц Өгөгдлийн_санд_өгөгдөл_нэмэх_2(Ажилчны мэдээлэл):
5. функц Өгөгдлийн_санг_хэвлэх(Өгөгдлийн_сан_1):
6. функц Өгөгдлийн_санг_хэвлэх(Өгөгдлийн_сан_2):
7. функц ангилах_шилжүүлэх():
8. функц Өгөгдлийн_санг_хэвлэх(Өгөгдлийн_сан_1):
9. функц Өгөгдлийн_санг_хэвлэх(Өгөгдлийн_сан_2):

In [ ]:
import sqlite3
import os
def transfer_all_data():
    conn_main = sqlite3.connect('main_database.db')
    cursor_main = conn_main.cursor()

    conn_backup = sqlite3.connect('backup_database.db')
    cursor_backup = conn_backup.cursor()

    try:
        cursor_main.execute("SELECT * FROM workers")
        all_workers = cursor_main.fetchall()

        if all_workers:
            cursor_backup.executemany("INSERT INTO workers (id, name, age, profession) VALUES (?, ?, ?, ?)", all_workers)
            conn_backup.commit()



            print("All data transferred successfully.")

        else:
            print("No data found in the main database.")

    except Exception as e:
        print("Error:", e)

    finally:
        conn_main.close()
        conn_backup.close()



def print_database_data(database_name):
    conn = sqlite3.connect(database_name)
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM workers")
    data = cursor.fetchall()

    if data:
        print(f"Data in {database_name}:")
        for row in data:
            print(row)
    else:
        print(f"No data found in {database_name}.")

    conn.close()

def insert_worker_1(id,name,age,profession):
    cursor1_main.execute('''
        INSERT INTO workers (id, name, age, profession)
        VALUES (?, ?, ?, ?)
    ''', (id, name, age, profession))
    conn1_main.commit()

def insert_worker_2(id,name,age,profession):
    cursor_backup.execute('''
        INSERT INTO workers (id, name, age, profession)
        VALUES (?, ?, ?, ?)
    ''', (id, name, age, profession))
    conn_backup.commit()
def transfer_to_temporary():
    conn_main = sqlite3.connect('main_database.db')
    cursor_main = conn_main.cursor()

    conn_temp = sqlite3.connect('temp.db')
    cursor_temp = conn_temp.cursor()

    try:
        cursor_main.execute("SELECT * FROM workers")
        all_workers = cursor_main.fetchall()

        if all_workers:
            cursor_temp.executemany("INSERT INTO workers (id, name, age, profession) VALUES (?, ?, ?, ?)", all_workers)
            conn_temp.commit()


        else:
            print("No data found in the main database.")

    except Exception as e:
        print("Error:", e)

    finally:
        conn_main.close()
        conn_temp.close()

def delete_from_main():
    conn_main = sqlite3.connect('main_database.db')
    cursor_main = conn_main.cursor()

    try:
        cursor_main.execute("DELETE FROM workers WHERE id LIKE 'B%'")
        conn_main.commit()

    except Exception as e:
        print("Error:", e)

    finally:
        conn_main.close()

def delete_similar_data():
    conn_backup = sqlite3.connect('backup_database.db')
    cursor_backup = conn_backup.cursor()

    conn1_main = sqlite3.connect('main_database.db')
    cursor1_main = conn1_main.cursor()

    try:
        cursor1_main.execute("SELECT * FROM workers")
        temp_data = cursor1_main.fetchall()

        for row in temp_data:
            cursor_backup.execute("DELETE FROM workers WHERE id = ?", (row[0],))

        conn_backup.commit()

    except Exception as e:
        print("Error:", e)

    finally:
        conn_backup.close()
        conn1_main.close()


#--------------------------------------------------

conn1_main = sqlite3.connect('main_database.db')
cursor1_main = conn1_main.cursor()

cursor1_main.execute('''
    CREATE TABLE IF NOT EXISTS workers (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        age INTEGER,
        profession TEXT
    )
''')


insert_worker_1("E011","John mayer", 30, "Software Engineer")
insert_worker_1("E012","John markoe", 40, "Software Engineer")
insert_worker_1("E013","John markoe", 40, "Software Engineer")
insert_worker_1("E014","John markoe", 40, "Software Engineer")
insert_worker_1("E015","John markoe", 40, "Software Engineer")
insert_worker_1("B012","John markoe", 40, "Software Engineer")
insert_worker_1("B013","John markoe", 40, "Software Engineer")
insert_worker_1("B014","John markoe", 40, "Software Engineer")



conn1_main.commit()
conn1_main.close()

#--------------------------------------------------

conn_backup = sqlite3.connect('backup_database.db')
cursor_backup = conn_backup.cursor()

cursor_backup.execute('''
    CREATE TABLE IF NOT EXISTS workers (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        age INTEGER,
        profession TEXT
    )
''')

insert_worker_2("C001","John Doe", 30, "Software Engineer")
insert_worker_2("C002","John Dafoe", 20, "Software Engineer")


conn_backup.commit()
conn_backup.close()

#--------------------------------------------------

print("Шилжүүлгийн өмнөх өгөгдлийн сан")
print_database_data('main_database.db')
print_database_data('backup_database.db')

transfer_all_data()
delete_from_main()
delete_similar_data()

print("Шилжүүлгийн дараах өгөгдлийн сан")

print_database_data('main_database.db')
print_database_data('backup_database.db')
os.remove('main_database.db')
os.remove('backup_database.db')

In [ ]:
import sqlite3
import os
def transfer_all_data():
    conn_main = sqlite3.connect('main_database.db')
    cursor_main = conn_main.cursor()

    conn_backup = sqlite3.connect('backup_database.db')
    cursor_backup = conn_backup.cursor()

    try:
        cursor_main.execute("SELECT * FROM workers")
        all_workers = cursor_main.fetchall()

        if all_workers:
            cursor_backup.executemany("INSERT INTO workers (id, name, age, profession) VALUES (?, ?, ?, ?)", all_workers)
            conn_backup.commit()

            cursor_main.execute("DELETE FROM workers")
            conn_main.commit()

            print("All data transferred successfully.")

        else:
            print("No data found in the main database.")

    except Exception as e:
        print("Error:", e)

    finally:
        conn_main.close()
        conn_backup.close()

def delete_from_temp():
    conn_temp = sqlite3.connect('temp.db')
    cursor_temp = conn_temp.cursor()

    try:
        cursor_temp.execute("DELETE FROM workers WHERE id LIKE 'B%'")
        conn_temp.commit()

    except Exception as e:
        print("Error:", e)

    finally:
        conn_temp.close()

def print_database_data(database_name):
    conn = sqlite3.connect(database_name)
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM workers")
    data = cursor.fetchall()

    if data:
        print(f"Data in {database_name}:")
        for row in data:
            print(row)
    else:
        print(f"No data found in {database_name}.")

    conn.close()

def insert_worker_1(id,name,age,profession):
    cursor1_main.execute('''
        INSERT INTO workers (id, name, age, profession)
        VALUES (?, ?, ?, ?)
    ''', (id, name, age, profession))
    conn1_main.commit()

def insert_worker_2(id,name,age,profession):
    cursor_backup.execute('''
        INSERT INTO workers (id, name, age, profession)
        VALUES (?, ?, ?, ?)
    ''', (id, name, age, profession))
    conn_backup.commit()

def transfer_to_temporary():
    conn_main = sqlite3.connect('main_database.db')
    cursor_main = conn_main.cursor()

    conn_temp = sqlite3.connect('temp.db')
    cursor_temp = conn_temp.cursor()

    try:
        cursor_main.execute("SELECT * FROM workers")
        all_workers = cursor_main.fetchall()

        if all_workers:
            cursor_temp.executemany("INSERT INTO workers (id, name, age, profession) VALUES (?, ?, ?, ?)", all_workers)
            conn_temp.commit()


        else:
            print("No data found in the main database.")

    except Exception as e:
        print("Error:", e)

    finally:
        conn_main.close()
        conn_temp.close()
def delete_similar_data():
    conn_backup = sqlite3.connect('backup_database.db')
    cursor_backup = conn_backup.cursor()

    conn_temp = sqlite3.connect('temp.db')
    cursor_temp = conn_temp.cursor()

    try:
        cursor_temp.execute("SELECT * FROM workers")
        temp_data = cursor_temp.fetchall()

        for row in temp_data:
            cursor_backup.execute("DELETE FROM workers WHERE id = ?", (row[0],))

        conn_backup.commit()

    except Exception as e:
        print("Error:", e)

    finally:
        conn_backup.close()
        conn_temp.close()
def transfer_from_temp_to_main():
    conn_temp = sqlite3.connect('temp.db')
    cursor_temp = conn_temp.cursor()

    conn_main = sqlite3.connect('main_database.db')
    cursor_main = conn_main.cursor()

    try:
        cursor_temp.execute("SELECT * FROM workers")
        all_temp_workers = cursor_temp.fetchall()

        if all_temp_workers:
            cursor_main.executemany("INSERT INTO workers (id, name, age, profession) VALUES (?, ?, ?, ?)", all_temp_workers)
            conn_main.commit()

            cursor_temp.execute("DELETE FROM workers")
            conn_temp.commit()

            print("All data transferred from temporary to main database successfully.")

        else:
            print("No data found in the temporary database.")

    except Exception as e:
        print("Error:", e)

    finally:
        conn_main.close()
        conn_temp.close()


conn_temp = sqlite3.connect('temp.db')
cursor_temp = conn_temp.cursor()

cursor_temp.execute('''
    CREATE TABLE IF NOT EXISTS workers (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        age INTEGER,
        profession TEXT
    )
''')
#--------------------------------------------------

conn1_main = sqlite3.connect('main_database.db')
cursor1_main = conn1_main.cursor()

cursor1_main.execute('''
    CREATE TABLE IF NOT EXISTS workers (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        age INTEGER,
        profession TEXT
    )
''')


insert_worker_1("E011","John mayer", 30, "Software Engineer")
insert_worker_1("E012","John markoe", 40, "Software Engineer")
insert_worker_1("E013","John markoe", 40, "Software Engineer")
insert_worker_1("E014","John markoe", 40, "Software Engineer")
insert_worker_1("E015","John markoe", 40, "Software Engineer")
insert_worker_1("B012","John markoe", 40, "Software Engineer")
insert_worker_1("B013","John markoe", 40, "Software Engineer")
insert_worker_1("B014","John markoe", 40, "Software Engineer")



conn1_main.commit()
conn1_main.close()

#--------------------------------------------------

conn_backup = sqlite3.connect('backup_database.db')
cursor_backup = conn_backup.cursor()

cursor_backup.execute('''
    CREATE TABLE IF NOT EXISTS workers (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        age INTEGER,
        profession TEXT
    )
''')

insert_worker_2("C001","John Doe", 30, "Software Engineer")
insert_worker_2("C002","John Dafoe", 20, "Software Engineer")


conn_backup.commit()
conn_backup.close()

#--------------------------------------------------
print("Шилжүүлгийн өмнөх өгөгдлийн сан")
print_database_data('main_database.db')
print_database_data('backup_database.db')

transfer_to_temporary()
delete_from_temp()
transfer_all_data()
delete_similar_data()
transfer_from_temp_to_main()

print("Шилжүүлгийн дараах өгөгдлийн сан")

print_database_data('main_database.db')
print_database_data('backup_database.db')
os.remove('main_database.db')
os.remove('backup_database.db')